name: Create PR to keep master branch in sync with develop branch

on:
  push:
    branches:
      - develop

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
        
      #- name: Update author information
        #run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: develop
          base: master
          title: "PR created using github workflow"
          #committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          #author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          
          body:
            The develop branch is a commit ahead of master branch.
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
