name: Create automatic PR

on:
  push:
    branches:
      - master

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "develop"
          base: master
          title: "Create auto pr using github workflow"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            Branch develop is a commit ahead. 
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
