name: Create automatic PR

on:
  push:
    branches:
      - master

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        run: gh pr create --base master --head develop --title "PR created by github actions" --body "Branch develop is a commit ahead"
